### ISSUE TITLE
Make sure Android screen doesn't sleep

### ISSUE THREAD

**Issue by dbaldwin** [dbaldwin/DronePan-Android#13]

**Comment by chschafl** [comment]
This seems to be a solution: http://stackoverflow.com/questions/3723634/how-do-i-prevent-an-android-device-from-going-to-sleep-programmatically

**Comment by plix-xyz** [comment]
Hello :) The first option in the below link, to use the FLAG_KEEP_SCREEN_ON in the activity, or equivalently using the  android:keepScreenOn attribute in the xml file, is a more lightweight solution, that is less likely to cause wakelock related issues.
https://developer.android.com/training/scheduling/wakelock.html#screen
